-- MySQL Script generated by MySQL Workbench
-- Tue Mar 24 17:23:16 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bddautoecole
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bddautoecole
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bddautoecole` DEFAULT CHARACTER SET utf8mb4;
USE `bddautoecole` ;

-- -----------------------------------------------------
-- Table `bddautoecole`.`adresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddautoecole`.`adresse` (
  `id` INT NOT NULL,
  `adresse` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bddautoecole`.`examen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddautoecole`.`examen` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bddautoecole`.`eleves`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddautoecole`.`eleves` (
  `id` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `birth` VARCHAR(45) NULL,
  `adresse_id` INT NOT NULL,
  `examen_id` INT NOT NULL,
  PRIMARY KEY (`id`, `adresse_id`),
  INDEX `fk_eleves_adresse1_idx` (`adresse_id` ASC) ,
  INDEX `fk_eleves_examen1_idx` (`examen_id` ASC) ,
  CONSTRAINT `fk_eleves_adresse1`
    FOREIGN KEY (`adresse_id`)
    REFERENCES `bddautoecole`.`adresse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eleves_examen1`
    FOREIGN KEY (`examen_id`)
    REFERENCES `bddautoecole`.`examen` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bddautoecole`.`CDrom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddautoecole`.`CDrom` (
  `numero` INT NOT NULL,
  `nomEditeur` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bddautoecole`.`serie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddautoecole`.`serie` (
  `id` INT NOT NULL,
  `CDrom_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_serie_CDrom1_idx` (`CDrom_id` ASC) ,
  CONSTRAINT `fk_serie_CDrom1`
    FOREIGN KEY (`CDrom_id`)
    REFERENCES `bddautoecole`.`CDrom` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bddautoecole`.`seance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddautoecole`.`seance` (
  `id` INT NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  `serie_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_seance_serie1_idx` (`serie_id` ASC) ,
  CONSTRAINT `fk_seance_serie1`
    FOREIGN KEY (`serie_id`)
    REFERENCES `bddautoecole`.`serie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bddautoecole`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddautoecole`.`questions` (
  `id` INT NOT NULL,
  `intitulé` VARCHAR(45) NOT NULL,
  `reponse` VARCHAR(45) NOT NULL,
  `difficulty` VARCHAR(45) NOT NULL,
  `theme` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bddautoecole`.`eleves_has_seance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddautoecole`.`eleves_has_seance` (
  `eleves_id` INT NOT NULL,
  `seance_id` INT NOT NULL,
  `nbfaute` INT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_eleves_has_seance_seance1_idx` (`seance_id` ASC) ,
  INDEX `fk_eleves_has_seance_eleves_idx` (`eleves_id` ASC) ,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_eleves_has_seance_eleves`
    FOREIGN KEY (`eleves_id`)
    REFERENCES `bddautoecole`.`eleves` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eleves_has_seance_seance1`
    FOREIGN KEY (`seance_id`)
    REFERENCES `bddautoecole`.`seance` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bddautoecole`.`questions_has_serie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddautoecole`.`questions_has_serie` (
  `questions_id` INT NOT NULL,
  `serie_id` INT NOT NULL,
  PRIMARY KEY (`questions_id`, `serie_id`),
  INDEX `fk_questions_has_serie_serie1_idx` (`serie_id` ASC) ,
  INDEX `fk_questions_has_serie_questions1_idx` (`questions_id` ASC) ,
  CONSTRAINT `fk_questions_has_serie_questions1`
    FOREIGN KEY (`questions_id`)
    REFERENCES `bddautoecole`.`questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questions_has_serie_serie1`
    FOREIGN KEY (`serie_id`)
    REFERENCES `bddautoecole`.`serie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
